apiVersion: v1
kind: Service
metadata:
  name: lofi-books-frontend
  namespace: lofi-books
spec:
  selector:
    app: lofi-books-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
