apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - frontend-service.yaml
  - frontend-deployment.yaml
  - backend-service.yaml
  - backend-deployment.yaml
  - pvc.yaml
  - network-policies.yaml
